%% Simple example with four classes
%
%% Description
% Draws a figure with 4 sets in the 4 quadrants of the figure. Each
% is the same size and divided at x = 2 and y = 2.
% This is a simple test of a decision tree.


% Vertices
v = [ 0 0;...
      0 4;...
      4 4;...
    	4 0;...
      2 4;...
      2 2;...
      2 0;...
      0 2;...
      4 2];
   
  % Faces
  f = { [6 5 2 8] [6 7 4 9] [6 9 3 5] [1 7 6 8] };
  
  ClassifierSets( 5, [0 4], [0 4], {'width', 'length'}, v, f );
